//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriteProducts
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Amount { get; set; }
        public string Sale { get; set; }
        public string Owner { get; set; }
        public string Price { get; set; }
        public string OldPrice { get; set; }
        public string ImageUrl { get; set; }
        public string OriginalLink { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
